class ApplicationException(Exception):
    ...

class ApplicationNotFoundException(ApplicationException):
    ...

class CantTouchDoneApplicationException(ApplicationException):
    ...

class CantSetStatusLess(ApplicationException):
    ...
