class AdminAuthException(Exception):
    ...

class AdminAlreadyExistsException(AdminAuthException):
    ...

class AdminNotFoundException(AdminAuthException):
    ...

class InvalidPasswordException(AdminAuthException):
    ...

class PermissionException(AdminAuthException):
    ...

class AdminDeletionException(AdminAuthException):
    ...

class InvalidTokenException(AdminAuthException):
    ...

class TokenExpireException(AdminAuthException):
    ...
